#pragma once

void toggleMatchload();
void toggleWing();
void toggleHood();
void toggleIndexer();
void toggleIntakeBSIWonderHowLongICanNameAFunctionTurnsOutItsPrettyLongIWonderWhyYoudEverDoThisButThatsCoolAmazeAmazeAmazeEpicFunctionSauceILikeBajaBlastAndLongFunctionNamesEpicSixtyNine();